In [6]:
import pandas as pd
import numpy as np

In [7]:
df= pd.read_csv("play_tennis.csv")
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [8]:
df.drop(columns="day",inplace=True)
df.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

# Problem 1

# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak
# Play or No Play?

# Solution

# P(Yes | Sunny,Hot,High,Weak)=P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | Yes) *P(Yes)

# P(No | Sunny,Hot,High,Weak)=P(Sunny | No) * P(Hot | No) * P(High | No) * P(Weak | No)*P(No)

# Compare and decide using the Maximum a posteriori rule

In [10]:
#training
#data is stored in the lookup table
#P(Yes) and #P(No)
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [11]:
py=9/14
pn=5/14

In [12]:
print("P(yes):",py)
print("P(No):",pn)

P(yes): 0.6428571428571429
P(No): 0.35714285714285715

In [14]:
#Outlook
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [16]:
# prob  p(n,x1,x2,x3)
p_overcast_n=0
p_rain_n=2/5
p_suuny_n=3/5

# prob  p(y,x1,x2,x3)
p_overcast_y=4/9
p_rain_y=3/9
p_suuny_y=2/9

In [ ]:
#Temp
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [18]:
# prob No  p(n,x1,x2,x3)
p_cool_n=1/5
p_hot_n=2/5
p_mild_n=2/5

# prob yes  p(n,x1,x2,x3)
p_cool_y=3/9
p_hot_y=2/9
p_mild_y=4/9

In [ ]:
#humidity
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [20]:
# prob No  p(n,x1,x2,x3)
p_high_n=4/5
p_normal_n=1/5

# prob yes  p(n,x1,x2,x3)
p_high_y=3/9
p_normal_y=6/9

In [21]:
#wind
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [22]:
# prob No  p(n,x1,x2,x3)
p_strong_n=3/5
p_weak_n=2/5

# prob yes  p(n,x1,x2,x3)
p_strong_y=3/9
p_weak_y=6/9

In [23]:
# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak
# Play or No Play?
p_yes=py*p_suuny_y*p_hot_y*p_high_y*p_weak_y
print(p_yes)

0.007054673721340388

In [24]:
p_No=pn*p_suuny_n*p_hot_n*p_high_n*p_weak_n
print(p_No)

0.02742857142857143

In [ ]:
#p(No)>p(yes) so "No Play"